## Numpy Array Slicing

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7,8,9,10,11])

print(arr[1:5])

[2 3 4 5]


In [6]:
# !pip install numpy


In [4]:
arr[:4]

array([1, 2, 3, 4])

In [5]:
print(arr[4:])

[ 5  6  7  8  9 10 11]


## Negative Slicing

In [7]:
print(arr[-3:-1])# start: end


[ 9 10]


In [8]:
## Step
print(arr[::2])## Step 2

[ 1  3  5  7  9 11]


In [9]:
print(arr[1:10:3])## step 3

[2 5 8]


In [10]:
## Slicing Two D arrays
two_d= np.array([[1, 2, 3],
                 [4, 5, 6]])

print(two_d)

[[1 2 3]
 [4 5 6]]


In [15]:
two_d[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
two_d[0:1,1]

array([2])

### Checking the datatypes of an Array

In [20]:
two_d.dtype

dtype('int32')

In [21]:
numpy_str = np.array(['apple', 'banana', 'cherry'])

print(numpy_str.dtype)

<U6


### Creating Arrays With a Defined Datatype

In [22]:
arr = np.array([6, 2, 8, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'6' b'2' b'8' b'4']
|S1


In [23]:
arr = np.array([6, 2, 8, 4], dtype='i4')

print(arr)
print(arr.dtype)

[6 2 8 4]
int32


### Converting Data Type on Existing Arrays

In [24]:
newarr= arr.astype('f')
print(newarr.dtype)

float32


In [25]:
newarr

array([6., 2., 8., 4.], dtype=float32)

In [27]:
newerarr=newarr.astype(int)
print(newerarr.dtype)

int32


In [29]:
latest=newerarr.astype(bool)
print(latest.dtype)

bool


In [30]:
latest

array([ True,  True,  True,  True])

### Numpy Array Copy Vs view

In [32]:

a = np.array([1, 8, 3, 4, 9])
x = a.copy()
a[0] = 21

print(a)
print(x)

[21  8  3  4  9]
[1 8 3 4 9]


In [33]:
b = a.view()
a[0]=23
print(a)
print(b)# The view

[23  8  3  4  9]
[23  8  3  4  9]


In [35]:
#if we make changes to the view, it should affect the original
b[1] = 45
print(a)
print(b)
# the changes in the view also reflects in the original array

[23 45  3  4  9]
[23 45  3  4  9]


In [36]:
# checking if an array owns its data
print(x.base)
print(b.base)

None
[23 45  3  4  9]
