## Introduction to Numpy







In [1]:
import numpy
ar = numpy.array([3,5,6,7,23])
print(ar)

[ 3  5  6  7 23]


In [2]:
# Alias naming numpy can also be given an alias name . In most cases it saved as np
import numpy as np

ar = np.array([3,5,6,7,23])
print(ar)

[ 3  5  6  7 23]


In [3]:
## Creating Numpy Arrays
type(ar)

numpy.ndarray

In [4]:
## It can turn lists, tuples into an array
ar = np.array((3,5,6,7,23))
print(ar)

[ 3  5  6  7 23]


In [5]:
# Scalar values
scalar = np.array(15)
print(scalar)
#Zero dimensional Array

15


In [6]:
## 1-D Array
ar = np.array([1, 3,  5])

print(ar)

[1 3 5]


In [8]:
two_d= np.array([[1, 2, 3],
                 [4, 5, 6]])

print(two_d)

[[1 2 3]
 [4 5 6]]


In [11]:

three_d = np.array([[[1, 2, 3],
                 [4, 5, 6]],
                
                [[1, 2, 3],
                 [4, 5, 6]]])

print(three_d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [12]:
print(scalar.ndim)
print(two_d.ndim)
print(three_d.ndim)

0
2
3


In [14]:
## We can create an array with multiple dimensions
One_d = np.array([1, 3,  5], ndmin=4)

print(One_d)
print('The nos of dimensions is ',One_d.ndim)

[[[[1 3 5]]]]
The nos of dimensions is  4
