## Numpy Array Shape

In [1]:
import numpy as np
two_d= np.array([[1, 2, 3],
                 [4, 5, 6]])

print(two_d.shape)

(2, 3)


In [3]:
arr = np.array([1,7 ,8, 3,5, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 7 8 3 5 4]]]]]
shape of array : (1, 1, 1, 1, 6)


In [6]:
two_d= np.array([[1, 2, 3,7,8],
                 [4, 5, 6,8,4,],
                 [7, 3, 7,2,3,]
                ])

print(two_d.shape)

(3, 5)


# Numpy Array Reshaping

In [8]:
# 1 Dimension to 2 Dimension

one_dim = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

new_shape = one_dim.reshape(4, 3)

In [9]:
print(new_shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
ano_shape =one_dim.reshape(6,2)
print(ano_shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [11]:
nwshape=one_dim.reshape(3,4)
print(nwshape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Reshape from 1 Dimension to 3 Dimension

In [12]:
newarr = one_dim.reshape(2,2,3)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [14]:
print(newarr.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Unknown Dimension

In [15]:
another_one=one_dim.reshape(2,2,-1)
print(another_one)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [16]:
##Flattening the array
arr =another_one.reshape(-1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Iterating Arrays Using nditer()

In [18]:
# for us to be able to loop into multidimension
#nditer is always used
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [20]:
for x in arr:
    for a in x:
        for y in a:
            print(y)#a longer process uding for loop

1
2
3
4
5
6
7
8


In [21]:
# Iterating Array with differnt datatype
a = np.array([1, 2, 3])

for x in np.nditer(a, flags=['buffered'], op_dtypes=['S']):
      print(x)

b'1'
b'2'
b'3'


In [22]:
#Iterating with different step size
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


## Enumerate Iteration

In [23]:

for idx, x in np.ndenumerate(one_dim):
      print(idx, x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10
(10,) 11
(11,) 12


In [24]:
# Enumerate 2 d arrays
for idx, x in np.ndenumerate(arr):
      print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


### Numpy Joining Array

In [26]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr2, arr1))

print(arr)

[4 5 6 1 2 3]


In [27]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [28]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)# you can indicate the new axis to stack

[[1 4]
 [2 5]
 [3 6]]


In [32]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr)

[[1 2 3]
 [4 5 6]]


### Stacking along the rows

In [29]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)# 

[1 2 3 4 5 6]


In [30]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [31]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
