In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [2]:
n= np.array_split(arr, 4)

print(n)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [3]:
s= np.split(arr, 4)# print out an error

print(s)

ValueError: array split does not result in an equal division

In [4]:
#Access the splitted arrays
print(n[0])#The splitted arrays can be indexed
print(n[1])
print(n[2])

[1 2]
[3 4]
[5]


## Splitting 2-D Arrays

In [5]:
two_dim=np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12],[13,14],[15,16]])

two_di=np.array_split(two_dim,4) 
print(two_di)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]]), array([[13, 14],
       [15, 16]])]


In [6]:
two_dim=np.array([[1, 2],
                  [3, 4], 
                  [5, 6], 
                  [7, 8], 
                  [9, 10], [11, 12],[13,14],[15,16]])

two_di=np.array_split(two_dim,4,axis=1) 
print(two_di)# you can split the array along the row

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16]]), array([], shape=(8, 0), dtype=int32), array([], shape=(8, 0), dtype=int32)]


In [7]:
nwarr = np.hsplit(arr, 3)

print(nwarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


### Numpy Searching Array 

In [8]:
arr = np.array([1, 2, 3, 4,2, 5, 7,6,6, 8,10])
where = np.where(arr==6)
print(where)# indicates the index location

(array([7, 8], dtype=int64),)


In [9]:
even= np.where(arr%2 == 0)

print(even)


(array([ 1,  3,  4,  7,  8,  9, 10], dtype=int64),)


In [10]:
odd= np.where(arr%2 == 0)

print(odd)


(array([ 1,  3,  4,  7,  8,  9, 10], dtype=int64),)


## Search Sorted

In [11]:
six = np.searchsorted(arr, 6)
print(six)

6


In [12]:
right = np.searchsorted(arr, 6,side='right')# you can also indicate the side
print(right)

9


## Sorting Arrays

In [13]:
print(np.sort(arr))

[ 1  2  2  3  4  5  6  6  7  8 10]


In [14]:

boo = np.array([True, False, True,False])

print(np.sort(boo))

[False False  True  True]


### Sorting a 2-D array

In [15]:


print(np.sort(two_dim))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


### Numpy Filter Array

In [16]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [17]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
      if element > 42:
        filter_arr.append(True)
      else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


 ### Creating a filter Directly from an Array

In [18]:

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


## Random Numbers